"""
02_generate_sample_data.py
---------------------------------------------------------------------
IMPORTANT: This script generates a SYNTHETIC stand-in dataset that
mirrors the real schema and category values of the public CFPB
Consumer Complaint Database (bigquery-public-data.cfpb_complaints.
complaint_database). It exists ONLY so the rest of this pipeline can
be tested and demoed without a live GCP connection.

For the real project, replace this step with
`scripts/05_bigquery_connector.py`, which pulls genuine complaint
records straight from BigQuery's public dataset (see the README).

Do NOT present numbers generated by this script as real findings --
they are illustrative only.
---------------------------------------------------------------------
"""
import random
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

random.seed(42)
np.random.seed(42)

N_ROWS = 6000

# Real CFPB category values (product -> plausible issues), based on the
# public field reference (cfpb.github.io/api/ccdb/fields.html) and the
# well-documented category taxonomy of the live dataset.
PRODUCT_ISSUES = {
    "Credit reporting, credit repair services, or other personal consumer reports": [
        "Incorrect information on your report",
        "Improper use of your report",
        "Problem with a credit reporting company's investigation",
    ],
    "Debt collection": [
        "Attempts to collect debt not owed",
        "Written notification about debt",
        "False statements or representation",
        "Communication tactics",
    ],
    "Credit card or prepaid card": [
        "Problem with a purchase shown on your statement",
        "Fees or interest",
        "Closing your account",
        "Getting a credit card",
    ],
    "Checking or savings account": [
        "Managing an account",
        "Problem caused by your funds being low",
        "Opening an account",
    ],
    "Mortgage": [
        "Trouble during payment process",
        "Struggling to pay mortgage",
        "Applying for a mortgage",
    ],
    "Student loan": [
        "Dealing with your lender or servicer",
        "Struggling to repay your loan",
    ],
    "Money transfer, virtual currency, or money service": [
        "Fraud or scam",
        "Problem with a lender or other company charging your account",
    ],
}

COMPANIES = [
    "Acme Financial Services", "Northgate Bank", "Summit Card Services",
    "Redwood Lending Group", "Coastal Credit Union", "Harbor Trust Bank",
    "Pinnacle Servicing LLC", "Union Point Financial", "Cedarbrook Bank",
    "Vantage Capital Partners",
]

STATES = ["CA", "TX", "FL", "NY", "IL", "PA", "OH", "GA", "NC", "MI",
          "NJ", "VA", "WA", "AZ", "MA", "TN", "IN", "MO", "MD", "WI"]

SUBMITTED_VIA = ["Web", "Referral", "Phone", "Postal mail", "Email", "Fax"]

RESPONSE_TYPES = ["Closed with explanation", "Closed with non-monetary relief",
                   "Closed with monetary relief", "Closed without relief",
                   "In progress"]

# Templated narrative fragments per issue -- keeps a genuine, learnable
# text->label signal for the classifier step without using any real
# consumer narratives.
NARRATIVE_TEMPLATES = {
    "Incorrect information on your report": [
        "There is an account on my credit report that does not belong to me and I have disputed it multiple times.",
        "My credit report shows a late payment that was never late, I have proof of on time payment.",
    ],
    "Improper use of your report": [
        "A company pulled my credit report without my permission for a purpose I never authorized.",
    ],
    "Problem with a credit reporting company's investigation": [
        "I filed a dispute over 30 days ago and the credit bureau has not corrected or responded to my investigation.",
    ],
    "Attempts to collect debt not owed": [
        "I am being contacted about a debt that I already paid off two years ago and have receipts to prove it.",
        "This collector is trying to collect a debt that is not mine, likely a case of mistaken identity.",
    ],
    "Written notification about debt": [
        "I never received the required written validation notice before collection calls started.",
    ],
    "False statements or representation": [
        "The collection agency threatened legal action that they have no authority to actually pursue.",
    ],
    "Communication tactics": [
        "I am receiving multiple collection calls per day, well beyond what is allowed under regulation.",
    ],
    "Problem with a purchase shown on your statement": [
        "There is a charge on my card statement for a purchase I never made or authorized.",
    ],
    "Fees or interest": [
        "I was charged an overdraft and interest fee that was never disclosed to me when I opened the account.",
    ],
    "Closing your account": [
        "My account was closed without any prior notice and I still had a positive balance.",
    ],
    "Getting a credit card": [
        "My credit card application was denied for reasons that were never clearly explained to me.",
    ],
    "Managing an account": [
        "I was unable to access my own checking account funds for over a week with no explanation.",
    ],
    "Problem caused by your funds being low": [
        "My account was overdrawn due to a hold the bank placed without telling me in advance.",
    ],
    "Opening an account": [
        "I was denied the ability to open a basic checking account without a clear reason given.",
    ],
    "Trouble during payment process": [
        "My mortgage servicer misapplied my monthly payment and then charged me a late fee.",
    ],
    "Struggling to pay mortgage": [
        "I requested a loan modification months ago and have not received any response from my servicer.",
    ],
    "Applying for a mortgage": [
        "My mortgage application has been delayed for months with no clear update from the lender.",
    ],
    "Dealing with your lender or servicer": [
        "My student loan servicer will not respond to my repeated requests about my repayment plan.",
    ],
    "Struggling to repay your loan": [
        "I applied for an income-driven repayment plan and my servicer never processed it correctly.",
    ],
    "Fraud or scam": [
        "Someone used my account to send a fraudulent money transfer and the company will not refund me.",
    ],
    "Problem with a lender or other company charging your account": [
        "A company charged my account for a transfer I never initiated or approved.",
    ],
}

GENERIC_OPENERS = [
    "I am writing to file a complaint. ",
    "To whom it may concern, ",
    "I would like to report the following issue. ",
    "This has been an ongoing problem. ",
    "",  # no opener, for variety
]
GENERIC_CLOSERS = [
    " I would appreciate a prompt resolution.",
    " Please investigate this matter.",
    " This has caused significant stress.",
    "",
]

rows = []
start_date = datetime(2023, 1, 1)
for i in range(N_ROWS):
    product = random.choice(list(PRODUCT_ISSUES.keys()))
    true_issue = random.choice(PRODUCT_ISSUES[product])

    # Realism knob: ~18% of the time, pull the narrative from a
    # *different* (confusable) issue under the same product -- real
    # consumer narratives routinely blur adjacent Issue boundaries,
    # which is exactly what a validation exercise should surface.
    if random.random() < 0.18 and len(PRODUCT_ISSUES[product]) > 1:
        narrative_issue = random.choice(
            [i2 for i2 in PRODUCT_ISSUES[product] if i2 != true_issue]
        )
    else:
        narrative_issue = true_issue

    base_narrative = random.choice(NARRATIVE_TEMPLATES[narrative_issue])
    narrative = (random.choice(GENERIC_OPENERS) + base_narrative
                 + random.choice(GENERIC_CLOSERS))
    issue = true_issue  # the label stays the ground-truth Issue
    days_offset = random.randint(0, 900)
    date_received = start_date + timedelta(days=days_offset)
    timely = np.random.choice(["Yes", "No"], p=[0.92, 0.08])
    disputed = np.random.choice(["Yes", "No"], p=[0.18, 0.82])

    rows.append({
        "complaint_id": 3000000 + i,
        "date_received": date_received.strftime("%Y-%m-%d"),
        "product": product,
        "issue": issue,
        "consumer_complaint_narrative": narrative,
        "company": random.choice(COMPANIES),
        "state": random.choice(STATES),
        "submitted_via": random.choice(SUBMITTED_VIA),
        "company_response_to_consumer": random.choice(RESPONSE_TYPES),
        "timely_response": timely,
        "consumer_disputed": disputed,
    })

df = pd.DataFrame(rows)
df.to_csv("/home/claude/complaints_project/data/sample_complaints.csv", index=False)
print(f"Wrote {len(df)} synthetic rows to data/sample_complaints.csv")
print(df.head(3).to_string())
